language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python manage.py test
notifications:
  email:
    recipients:
      - johndavidsimmons@gmail.com
    on_success: always # default: change
    on_failure: always # default: always