"""user

Revision ID: 112473ade012
Revises: 22618af03a34
Create Date: 2016-10-11 23:11:05.501102

"""

# revision identifiers, used by Alembic.
revision = '112473ade012'
down_revision = '22618af03a34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
