"""changed user name

Revision ID: 11ac3dc5881c
Revises: 51427c7d4dcf
Create Date: 2016-10-20 14:25:48.761266

"""

# revision identifiers, used by Alembic.
revision = '11ac3dc5881c'
down_revision = '51427c7d4dcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
