"""migrate test

Revision ID: 179542073322
Revises: 5342eb3e3ae8
Create Date: 2016-10-18 20:50:09.186899

"""

# revision identifiers, used by Alembic.
revision = '179542073322'
down_revision = '5342eb3e3ae8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('migrate_test', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'migrate_test')
    ### end Alembic commands ###
