"""yolo

Revision ID: 1c89484b900c
Revises: 112473ade012
Create Date: 2016-10-15 14:04:23.550641

"""

# revision identifiers, used by Alembic.
revision = '1c89484b900c'
down_revision = '112473ade012'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
