"""empty message

Revision ID: 1df48d465284
Revises: 37305d1b806b
Create Date: 2016-10-20 14:12:14.213198

"""

# revision identifiers, used by Alembic.
revision = '1df48d465284'
down_revision = '37305d1b806b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
