"""pw hash

Revision ID: 1e683113bdb
Revises: addc88d91ac
Create Date: 2016-09-22 17:09:35.681237

"""

# revision identifiers, used by Alembic.
revision = '1e683113bdb'
down_revision = 'addc88d91ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
