"""gravatar

Revision ID: 22618af03a34
Revises: 51ae62159b02
Create Date: 2016-10-07 15:19:36.642428

"""

# revision identifiers, used by Alembic.
revision = '22618af03a34'
down_revision = '51ae62159b02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
