"""initial migration

Revision ID: 292dc953d445
Revises: None
Create Date: 2016-09-22 13:46:03.437375

"""

# revision identifiers, used by Alembic.
revision = '292dc953d445'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
