"""rm rel table

Revision ID: 2e2cebf05ce9
Revises: 512c50a964ef
Create Date: 2016-12-06 20:39:30.626160

"""

# revision identifiers, used by Alembic.
revision = '2e2cebf05ce9'
down_revision = '512c50a964ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_table')
    op.add_column('titles', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('titles', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'timestamp')
    op.drop_column('titles', 'owner_id')
    op.create_table('relationship_table',
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('title_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], [u'users_table.id'], ),
    sa.ForeignKeyConstraint(['title_id'], [u'titles.id'], )
    )
    ### end Alembic commands ###
