"""confirmation typo fixed

Revision ID: 2e98dc1a9580
Revises: b482a8e74aa
Create Date: 2016-09-23 21:39:26.135539

"""

# revision identifiers, used by Alembic.
revision = '2e98dc1a9580'
down_revision = 'b482a8e74aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
