"""empty message

Revision ID: 37305d1b806b
Revises: 179542073322
Create Date: 2016-10-18 21:44:40.942769

"""

# revision identifiers, used by Alembic.
revision = '37305d1b806b'
down_revision = '179542073322'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
