"""fake data

Revision ID: 38ce97f49edf
Revises: 30e5e063430f
Create Date: 2016-11-25 23:13:08.400072

"""

# revision identifiers, used by Alembic.
revision = '38ce97f49edf'
down_revision = '30e5e063430f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
