"""user local time

Revision ID: 4401a1643801
Revises: 2e2cebf05ce9
Create Date: 2016-12-07 22:43:50.884047

"""

# revision identifiers, used by Alembic.
revision = '4401a1643801'
down_revision = '2e2cebf05ce9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
