"""default role id

Revision ID: 4d4db67d840b
Revises: 1e683113bdb
Create Date: 2016-09-23 16:15:45.168171

"""

# revision identifiers, used by Alembic.
revision = '4d4db67d840b'
down_revision = '1e683113bdb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
