"""initial

Revision ID: 4f700bb2593d
Revises: None
Create Date: 2016-10-21 14:46:28.411475

"""

# revision identifiers, used by Alembic.
revision = '4f700bb2593d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
