"""yolo

Revision ID: 5342eb3e3ae8
Revises: 1c89484b900c
Create Date: 2016-10-17 20:07:28.017464

"""

# revision identifiers, used by Alembic.
revision = '5342eb3e3ae8'
down_revision = '1c89484b900c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
