"""password reset

Revision ID: 5a46a7e87523
Revises: 2e98dc1a9580
Create Date: 2016-09-28 22:43:27.816974

"""

# revision identifiers, used by Alembic.
revision = '5a46a7e87523'
down_revision = '2e98dc1a9580'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
