"""user local time

Revision ID: 5de59f042b6
Revises: 4401a1643801
Create Date: 2016-12-07 22:48:38.500992

"""

# revision identifiers, used by Alembic.
revision = '5de59f042b6'
down_revision = '4401a1643801'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
