"""user pw

Revision ID: addc88d91ac
Revises: 292dc953d445
Create Date: 2016-09-22 16:55:58.543651

"""

# revision identifiers, used by Alembic.
revision = 'addc88d91ac'
down_revision = '292dc953d445'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
