"""confirmation

Revision ID: b482a8e74aa
Revises: 4d4db67d840b
Create Date: 2016-09-23 21:36:40.222947

"""

# revision identifiers, used by Alembic.
revision = 'b482a8e74aa'
down_revision = '4d4db67d840b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
