"""drop owned

Revision ID: face58d015d
Revises: 1b4796c78793
Create Date: 2016-12-04 17:25:48.723491

"""

# revision identifiers, used by Alembic.
revision = 'face58d015d'
down_revision = '1b4796c78793'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
